// Code generated by MockGen. DO NOT EDIT.
// Source: audit.go
//
// Generated by this command:
//
//	mockgen -source=audit.go -destination=../../mocks/audit.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	audit "github.com/xcreativs/caliber/internal/domain/audit"
	kernel "github.com/xcreativs/caliber/internal/domain/kernel"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockAuditRepository) Append(ctx context.Context, entry *audit.AuditEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockAuditRepositoryMockRecorder) Append(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockAuditRepository)(nil).Append), ctx, entry)
}

// List mocks base method.
func (m *MockAuditRepository) List(ctx context.Context, entity string, entityID kernel.ID, page kernel.Page) ([]*audit.AuditEntry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, entity, entityID, page)
	ret0, _ := ret[0].([]*audit.AuditEntry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAuditRepositoryMockRecorder) List(ctx, entity, entityID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuditRepository)(nil).List), ctx, entity, entityID, page)
}
