// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=../mocks/auth.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	app "github.com/xcreativs/caliber/internal/app"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordHasher is a mock of PasswordHasher interface.
type MockPasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHasherMockRecorder
	isgomock struct{}
}

// MockPasswordHasherMockRecorder is the mock recorder for MockPasswordHasher.
type MockPasswordHasherMockRecorder struct {
	mock *MockPasswordHasher
}

// NewMockPasswordHasher creates a new mock instance.
func NewMockPasswordHasher(ctrl *gomock.Controller) *MockPasswordHasher {
	mock := &MockPasswordHasher{ctrl: ctrl}
	mock.recorder = &MockPasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHasher) EXPECT() *MockPasswordHasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockPasswordHasher) Hash(plain string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", plain)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockPasswordHasherMockRecorder) Hash(plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockPasswordHasher)(nil).Hash), plain)
}

// Verify mocks base method.
func (m *MockPasswordHasher) Verify(encodedHash, plain string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", encodedHash, plain)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockPasswordHasherMockRecorder) Verify(encodedHash, plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockPasswordHasher)(nil).Verify), encodedHash, plain)
}

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// IssueAccess mocks base method.
func (m *MockTokenService) IssueAccess(p app.Principal) (app.AccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAccess", p)
	ret0, _ := ret[0].(app.AccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccess indicates an expected call of IssueAccess.
func (mr *MockTokenServiceMockRecorder) IssueAccess(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccess", reflect.TypeOf((*MockTokenService)(nil).IssueAccess), p)
}

// IssueRefresh mocks base method.
func (m *MockTokenService) IssueRefresh(p app.Principal) (app.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueRefresh", p)
	ret0, _ := ret[0].(app.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueRefresh indicates an expected call of IssueRefresh.
func (mr *MockTokenServiceMockRecorder) IssueRefresh(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueRefresh", reflect.TypeOf((*MockTokenService)(nil).IssueRefresh), p)
}

// VerifyAccess mocks base method.
func (m *MockTokenService) VerifyAccess(token string) (app.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccess", token)
	ret0, _ := ret[0].(app.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAccess indicates an expected call of VerifyAccess.
func (mr *MockTokenServiceMockRecorder) VerifyAccess(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccess", reflect.TypeOf((*MockTokenService)(nil).VerifyAccess), token)
}

// VerifyRefresh mocks base method.
func (m *MockTokenService) VerifyRefresh(token string) (app.RefreshClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRefresh", token)
	ret0, _ := ret[0].(app.RefreshClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRefresh indicates an expected call of VerifyRefresh.
func (mr *MockTokenServiceMockRecorder) VerifyRefresh(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRefresh", reflect.TypeOf((*MockTokenService)(nil).VerifyRefresh), token)
}
