// Code generated by MockGen. DO NOT EDIT.
// Source: port.go
//
// Generated by this command:
//
//	mockgen -source=port.go -destination=../../mocks/candidateagent.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	candidateagent "github.com/xcreativs/caliber/internal/domain/candidateagent"
	kernel "github.com/xcreativs/caliber/internal/domain/kernel"
	gomock "go.uber.org/mock/gomock"
)

// MockApplicationRepository is a mock of ApplicationRepository interface.
type MockApplicationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationRepositoryMockRecorder
	isgomock struct{}
}

// MockApplicationRepositoryMockRecorder is the mock recorder for MockApplicationRepository.
type MockApplicationRepositoryMockRecorder struct {
	mock *MockApplicationRepository
}

// NewMockApplicationRepository creates a new mock instance.
func NewMockApplicationRepository(ctrl *gomock.Controller) *MockApplicationRepository {
	mock := &MockApplicationRepository{ctrl: ctrl}
	mock.recorder = &MockApplicationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationRepository) EXPECT() *MockApplicationRepositoryMockRecorder {
	return m.recorder
}

// ByCandidate mocks base method.
func (m *MockApplicationRepository) ByCandidate(ctx context.Context, candidateID kernel.ID, page kernel.Page) ([]*candidateagent.Application, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByCandidate", ctx, candidateID, page)
	ret0, _ := ret[0].([]*candidateagent.Application)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ByCandidate indicates an expected call of ByCandidate.
func (mr *MockApplicationRepositoryMockRecorder) ByCandidate(ctx, candidateID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByCandidate", reflect.TypeOf((*MockApplicationRepository)(nil).ByCandidate), ctx, candidateID, page)
}

// ByID mocks base method.
func (m *MockApplicationRepository) ByID(ctx context.Context, id kernel.ID) (*candidateagent.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*candidateagent.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockApplicationRepositoryMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockApplicationRepository)(nil).ByID), ctx, id)
}

// Create mocks base method.
func (m *MockApplicationRepository) Create(ctx context.Context, app *candidateagent.Application) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApplicationRepositoryMockRecorder) Create(ctx, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApplicationRepository)(nil).Create), ctx, app)
}

// Update mocks base method.
func (m *MockApplicationRepository) Update(ctx context.Context, app *candidateagent.Application) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApplicationRepositoryMockRecorder) Update(ctx, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApplicationRepository)(nil).Update), ctx, app)
}
