// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=../../mocks/contest.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	contest "github.com/xcreativs/caliber/internal/domain/contest"
	kernel "github.com/xcreativs/caliber/internal/domain/kernel"
	gomock "go.uber.org/mock/gomock"
)

// MockContestRepository is a mock of ContestRepository interface.
type MockContestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContestRepositoryMockRecorder
	isgomock struct{}
}

// MockContestRepositoryMockRecorder is the mock recorder for MockContestRepository.
type MockContestRepositoryMockRecorder struct {
	mock *MockContestRepository
}

// NewMockContestRepository creates a new mock instance.
func NewMockContestRepository(ctrl *gomock.Controller) *MockContestRepository {
	mock := &MockContestRepository{ctrl: ctrl}
	mock.recorder = &MockContestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContestRepository) EXPECT() *MockContestRepositoryMockRecorder {
	return m.recorder
}

// ByCandidate mocks base method.
func (m *MockContestRepository) ByCandidate(ctx context.Context, candidateID kernel.ID, page kernel.Page) ([]*contest.Contest, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByCandidate", ctx, candidateID, page)
	ret0, _ := ret[0].([]*contest.Contest)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ByCandidate indicates an expected call of ByCandidate.
func (mr *MockContestRepositoryMockRecorder) ByCandidate(ctx, candidateID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByCandidate", reflect.TypeOf((*MockContestRepository)(nil).ByCandidate), ctx, candidateID, page)
}

// ByID mocks base method.
func (m *MockContestRepository) ByID(ctx context.Context, id kernel.ID) (*contest.Contest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*contest.Contest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockContestRepositoryMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockContestRepository)(nil).ByID), ctx, id)
}

// BySubject mocks base method.
func (m *MockContestRepository) BySubject(ctx context.Context, subjectID kernel.ID, page kernel.Page) ([]*contest.Contest, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BySubject", ctx, subjectID, page)
	ret0, _ := ret[0].([]*contest.Contest)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BySubject indicates an expected call of BySubject.
func (mr *MockContestRepositoryMockRecorder) BySubject(ctx, subjectID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BySubject", reflect.TypeOf((*MockContestRepository)(nil).BySubject), ctx, subjectID, page)
}

// Create mocks base method.
func (m *MockContestRepository) Create(ctx context.Context, c *contest.Contest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockContestRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContestRepository)(nil).Create), ctx, c)
}

// Update mocks base method.
func (m *MockContestRepository) Update(ctx context.Context, c *contest.Contest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockContestRepositoryMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContestRepository)(nil).Update), ctx, c)
}
