// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../mocks/interview.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interview "github.com/xcreativs/caliber/internal/domain/interview"
	kernel "github.com/xcreativs/caliber/internal/domain/kernel"
	gomock "go.uber.org/mock/gomock"
)

// MockInterviewRepository is a mock of InterviewRepository interface.
type MockInterviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInterviewRepositoryMockRecorder
	isgomock struct{}
}

// MockInterviewRepositoryMockRecorder is the mock recorder for MockInterviewRepository.
type MockInterviewRepositoryMockRecorder struct {
	mock *MockInterviewRepository
}

// NewMockInterviewRepository creates a new mock instance.
func NewMockInterviewRepository(ctrl *gomock.Controller) *MockInterviewRepository {
	mock := &MockInterviewRepository{ctrl: ctrl}
	mock.recorder = &MockInterviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterviewRepository) EXPECT() *MockInterviewRepositoryMockRecorder {
	return m.recorder
}

// ByCandidate mocks base method.
func (m *MockInterviewRepository) ByCandidate(ctx context.Context, candidateID kernel.ID, page kernel.Page) ([]*interview.Interview, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByCandidate", ctx, candidateID, page)
	ret0, _ := ret[0].([]*interview.Interview)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ByCandidate indicates an expected call of ByCandidate.
func (mr *MockInterviewRepositoryMockRecorder) ByCandidate(ctx, candidateID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByCandidate", reflect.TypeOf((*MockInterviewRepository)(nil).ByCandidate), ctx, candidateID, page)
}

// ByID mocks base method.
func (m *MockInterviewRepository) ByID(ctx context.Context, id kernel.ID) (*interview.Interview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*interview.Interview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockInterviewRepositoryMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockInterviewRepository)(nil).ByID), ctx, id)
}

// Create mocks base method.
func (m *MockInterviewRepository) Create(ctx context.Context, i *interview.Interview) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInterviewRepositoryMockRecorder) Create(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInterviewRepository)(nil).Create), ctx, i)
}

// Update mocks base method.
func (m *MockInterviewRepository) Update(ctx context.Context, i *interview.Interview) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInterviewRepositoryMockRecorder) Update(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInterviewRepository)(nil).Update), ctx, i)
}
