// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/matching/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/matching/ports.go -destination=internal/mocks/matching.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kernel "github.com/xcreativs/caliber/internal/domain/kernel"
	matching "github.com/xcreativs/caliber/internal/domain/matching"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchRepository is a mock of MatchRepository interface.
type MockMatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchRepositoryMockRecorder
	isgomock struct{}
}

// MockMatchRepositoryMockRecorder is the mock recorder for MockMatchRepository.
type MockMatchRepositoryMockRecorder struct {
	mock *MockMatchRepository
}

// NewMockMatchRepository creates a new mock instance.
func NewMockMatchRepository(ctrl *gomock.Controller) *MockMatchRepository {
	mock := &MockMatchRepository{ctrl: ctrl}
	mock.recorder = &MockMatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchRepository) EXPECT() *MockMatchRepositoryMockRecorder {
	return m.recorder
}

// ByRole mocks base method.
func (m *MockMatchRepository) ByRole(ctx context.Context, roleID kernel.ID, page kernel.Page) ([]*matching.Match, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByRole", ctx, roleID, page)
	ret0, _ := ret[0].([]*matching.Match)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ByRole indicates an expected call of ByRole.
func (mr *MockMatchRepositoryMockRecorder) ByRole(ctx, roleID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByRole", reflect.TypeOf((*MockMatchRepository)(nil).ByRole), ctx, roleID, page)
}

// ForCandidate mocks base method.
func (m *MockMatchRepository) ForCandidate(ctx context.Context, candidateID kernel.ID, page kernel.Page) ([]*matching.Match, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForCandidate", ctx, candidateID, page)
	ret0, _ := ret[0].([]*matching.Match)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ForCandidate indicates an expected call of ForCandidate.
func (mr *MockMatchRepositoryMockRecorder) ForCandidate(ctx, candidateID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForCandidate", reflect.TypeOf((*MockMatchRepository)(nil).ForCandidate), ctx, candidateID, page)
}

// Upsert mocks base method.
func (m_2 *MockMatchRepository) Upsert(ctx context.Context, m *matching.Match) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Upsert", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockMatchRepositoryMockRecorder) Upsert(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockMatchRepository)(nil).Upsert), ctx, m)
}
