// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/matching/recaller.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/matching/recaller.go -destination=internal/mocks/recaller.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kernel "github.com/xcreativs/caliber/internal/domain/kernel"
	gomock "go.uber.org/mock/gomock"
)

// MockCandidateRecaller is a mock of CandidateRecaller interface.
type MockCandidateRecaller struct {
	ctrl     *gomock.Controller
	recorder *MockCandidateRecallerMockRecorder
	isgomock struct{}
}

// MockCandidateRecallerMockRecorder is the mock recorder for MockCandidateRecaller.
type MockCandidateRecallerMockRecorder struct {
	mock *MockCandidateRecaller
}

// NewMockCandidateRecaller creates a new mock instance.
func NewMockCandidateRecaller(ctrl *gomock.Controller) *MockCandidateRecaller {
	mock := &MockCandidateRecaller{ctrl: ctrl}
	mock.recorder = &MockCandidateRecallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCandidateRecaller) EXPECT() *MockCandidateRecallerMockRecorder {
	return m.recorder
}

// Recall mocks base method.
func (m *MockCandidateRecaller) Recall(ctx context.Context, roleEmbedding []float32, limit int) ([]kernel.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recall", ctx, roleEmbedding, limit)
	ret0, _ := ret[0].([]kernel.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recall indicates an expected call of Recall.
func (mr *MockCandidateRecallerMockRecorder) Recall(ctx, roleEmbedding, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recall", reflect.TypeOf((*MockCandidateRecaller)(nil).Recall), ctx, roleEmbedding, limit)
}
