// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../mocks/role_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kernel "github.com/xcreativs/caliber/internal/domain/kernel"
	role "github.com/xcreativs/caliber/internal/domain/role"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// ByID mocks base method.
func (m *MockRoleRepository) ByID(ctx context.Context, id kernel.ID) (*role.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*role.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockRoleRepositoryMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockRoleRepository)(nil).ByID), ctx, id)
}

// Create mocks base method.
func (m *MockRoleRepository) Create(ctx context.Context, r *role.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoleRepositoryMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleRepository)(nil).Create), ctx, r)
}

// ListByEmployer mocks base method.
func (m *MockRoleRepository) ListByEmployer(ctx context.Context, employerID kernel.ID, page kernel.Page) ([]*role.Role, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEmployer", ctx, employerID, page)
	ret0, _ := ret[0].([]*role.Role)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByEmployer indicates an expected call of ListByEmployer.
func (mr *MockRoleRepositoryMockRecorder) ListByEmployer(ctx, employerID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEmployer", reflect.TypeOf((*MockRoleRepository)(nil).ListByEmployer), ctx, employerID, page)
}

// ListOpen mocks base method.
func (m *MockRoleRepository) ListOpen(ctx context.Context, page kernel.Page) ([]*role.Role, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpen", ctx, page)
	ret0, _ := ret[0].([]*role.Role)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOpen indicates an expected call of ListOpen.
func (mr *MockRoleRepositoryMockRecorder) ListOpen(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpen", reflect.TypeOf((*MockRoleRepository)(nil).ListOpen), ctx, page)
}

// Update mocks base method.
func (m *MockRoleRepository) Update(ctx context.Context, r *role.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoleRepositoryMockRecorder) Update(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleRepository)(nil).Update), ctx, r)
}
