// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/talent/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/talent/ports.go -destination=internal/mocks/talent.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kernel "github.com/xcreativs/caliber/internal/domain/kernel"
	talent "github.com/xcreativs/caliber/internal/domain/talent"
	gomock "go.uber.org/mock/gomock"
)

// MockCandidateRepository is a mock of CandidateRepository interface.
type MockCandidateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCandidateRepositoryMockRecorder
	isgomock struct{}
}

// MockCandidateRepositoryMockRecorder is the mock recorder for MockCandidateRepository.
type MockCandidateRepositoryMockRecorder struct {
	mock *MockCandidateRepository
}

// NewMockCandidateRepository creates a new mock instance.
func NewMockCandidateRepository(ctrl *gomock.Controller) *MockCandidateRepository {
	mock := &MockCandidateRepository{ctrl: ctrl}
	mock.recorder = &MockCandidateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCandidateRepository) EXPECT() *MockCandidateRepositoryMockRecorder {
	return m.recorder
}

// ByID mocks base method.
func (m *MockCandidateRepository) ByID(ctx context.Context, id kernel.ID) (*talent.Candidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*talent.Candidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockCandidateRepositoryMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockCandidateRepository)(nil).ByID), ctx, id)
}

// ByUserID mocks base method.
func (m *MockCandidateRepository) ByUserID(ctx context.Context, userID kernel.ID) (*talent.Candidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByUserID", ctx, userID)
	ret0, _ := ret[0].(*talent.Candidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByUserID indicates an expected call of ByUserID.
func (mr *MockCandidateRepositoryMockRecorder) ByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByUserID", reflect.TypeOf((*MockCandidateRepository)(nil).ByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockCandidateRepository) Create(ctx context.Context, c *talent.Candidate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCandidateRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCandidateRepository)(nil).Create), ctx, c)
}

// List mocks base method.
func (m *MockCandidateRepository) List(ctx context.Context, page kernel.Page) ([]*talent.Candidate, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page)
	ret0, _ := ret[0].([]*talent.Candidate)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCandidateRepositoryMockRecorder) List(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCandidateRepository)(nil).List), ctx, page)
}

// Update mocks base method.
func (m *MockCandidateRepository) Update(ctx context.Context, c *talent.Candidate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCandidateRepositoryMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCandidateRepository)(nil).Update), ctx, c)
}

// MockTalentProfileRepository is a mock of TalentProfileRepository interface.
type MockTalentProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTalentProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockTalentProfileRepositoryMockRecorder is the mock recorder for MockTalentProfileRepository.
type MockTalentProfileRepositoryMockRecorder struct {
	mock *MockTalentProfileRepository
}

// NewMockTalentProfileRepository creates a new mock instance.
func NewMockTalentProfileRepository(ctrl *gomock.Controller) *MockTalentProfileRepository {
	mock := &MockTalentProfileRepository{ctrl: ctrl}
	mock.recorder = &MockTalentProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTalentProfileRepository) EXPECT() *MockTalentProfileRepositoryMockRecorder {
	return m.recorder
}

// ByCandidateID mocks base method.
func (m *MockTalentProfileRepository) ByCandidateID(ctx context.Context, candidateID kernel.ID) (*talent.TalentProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByCandidateID", ctx, candidateID)
	ret0, _ := ret[0].(*talent.TalentProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByCandidateID indicates an expected call of ByCandidateID.
func (mr *MockTalentProfileRepositoryMockRecorder) ByCandidateID(ctx, candidateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByCandidateID", reflect.TypeOf((*MockTalentProfileRepository)(nil).ByCandidateID), ctx, candidateID)
}

// ByID mocks base method.
func (m *MockTalentProfileRepository) ByID(ctx context.Context, id kernel.ID) (*talent.TalentProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*talent.TalentProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockTalentProfileRepositoryMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockTalentProfileRepository)(nil).ByID), ctx, id)
}

// Create mocks base method.
func (m *MockTalentProfileRepository) Create(ctx context.Context, p *talent.TalentProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTalentProfileRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTalentProfileRepository)(nil).Create), ctx, p)
}

// List mocks base method.
func (m *MockTalentProfileRepository) List(ctx context.Context, page kernel.Page) ([]*talent.TalentProfile, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page)
	ret0, _ := ret[0].([]*talent.TalentProfile)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTalentProfileRepositoryMockRecorder) List(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTalentProfileRepository)(nil).List), ctx, page)
}

// Update mocks base method.
func (m *MockTalentProfileRepository) Update(ctx context.Context, p *talent.TalentProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTalentProfileRepositoryMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTalentProfileRepository)(nil).Update), ctx, p)
}
