global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "severity"]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: local-webhook

receivers:
  - name: local-webhook
    webhook_configs:
      - url: http://alertreceiver:8080/webhook
        send_resolved: true
