// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApplicationsByCandidate = `-- name: CountApplicationsByCandidate :one
SELECT count(*) FROM applications WHERE candidate_id = $1
`

func (q *Queries) CountApplicationsByCandidate(ctx context.Context, candidateID string) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsByCandidate, candidateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplication = `-- name: CreateApplication :exec
INSERT INTO applications (id, role_id, candidate_id, profile_id, source, tailored_summary, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
`

type CreateApplicationParams struct {
	ID              string
	RoleID          string
	CandidateID     string
	ProfileID       pgtype.Text
	Source          string
	TailoredSummary pgtype.Text
	Status          string
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) error {
	_, err := q.db.Exec(ctx, createApplication,
		arg.ID,
		arg.RoleID,
		arg.CandidateID,
		arg.ProfileID,
		arg.Source,
		arg.TailoredSummary,
		arg.Status,
	)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, role_id, candidate_id, profile_id, source, tailored_summary, status FROM applications WHERE id = $1
`

type GetApplicationRow struct {
	ID              string
	RoleID          string
	CandidateID     string
	ProfileID       pgtype.Text
	Source          string
	TailoredSummary pgtype.Text
	Status          string
}

func (q *Queries) GetApplication(ctx context.Context, id string) (GetApplicationRow, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i GetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.CandidateID,
		&i.ProfileID,
		&i.Source,
		&i.TailoredSummary,
		&i.Status,
	)
	return i, err
}

const listApplicationsByCandidate = `-- name: ListApplicationsByCandidate :many
SELECT id, role_id, candidate_id, profile_id, source, tailored_summary, status
FROM applications WHERE candidate_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListApplicationsByCandidateParams struct {
	CandidateID string
	Limit       int32
	Offset      int32
}

type ListApplicationsByCandidateRow struct {
	ID              string
	RoleID          string
	CandidateID     string
	ProfileID       pgtype.Text
	Source          string
	TailoredSummary pgtype.Text
	Status          string
}

func (q *Queries) ListApplicationsByCandidate(ctx context.Context, arg ListApplicationsByCandidateParams) ([]ListApplicationsByCandidateRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByCandidate, arg.CandidateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsByCandidateRow
	for rows.Next() {
		var i ListApplicationsByCandidateRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.CandidateID,
			&i.ProfileID,
			&i.Source,
			&i.TailoredSummary,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :execrows
UPDATE applications SET status = $2, tailored_summary = $3 WHERE id = $1
`

type UpdateApplicationParams struct {
	ID              string
	Status          string
	TailoredSummary pgtype.Text
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateApplication, arg.ID, arg.Status, arg.TailoredSummary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
