// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEntry = `-- name: AppendAuditEntry :exec
INSERT INTO audit_log (id, actor_user_id, action, entity, entity_id, before_json, after_json, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AppendAuditEntryParams struct {
	ID          string
	ActorUserID string
	Action      string
	Entity      string
	EntityID    string
	BeforeJson  []byte
	AfterJson   []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) error {
	_, err := q.db.Exec(ctx, appendAuditEntry,
		arg.ID,
		arg.ActorUserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.CreatedAt,
	)
	return err
}

const countAuditLog = `-- name: CountAuditLog :one
SELECT count(*) FROM audit_log WHERE entity = $1 AND entity_id = $2
`

type CountAuditLogParams struct {
	Entity   string
	EntityID string
}

func (q *Queries) CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLog, arg.Entity, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_user_id, action, entity, entity_id, before_json, after_json, created_at
FROM audit_log WHERE entity = $1 AND entity_id = $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListAuditLogParams struct {
	Entity   string
	EntityID string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.Entity,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
