// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidates.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCandidates = `-- name: CountCandidates :one
SELECT count(*) FROM candidates
`

func (q *Queries) CountCandidates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCandidates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCandidate = `-- name: CreateCandidate :exec
INSERT INTO candidates (id, user_id, location, preferences) VALUES ($1, $2, $3, $4)
`

type CreateCandidateParams struct {
	ID          string
	UserID      string
	Location    pgtype.Text
	Preferences []byte
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) error {
	_, err := q.db.Exec(ctx, createCandidate,
		arg.ID,
		arg.UserID,
		arg.Location,
		arg.Preferences,
	)
	return err
}

const getCandidate = `-- name: GetCandidate :one
SELECT id, user_id, location, preferences FROM candidates WHERE id = $1
`

type GetCandidateRow struct {
	ID          string
	UserID      string
	Location    pgtype.Text
	Preferences []byte
}

func (q *Queries) GetCandidate(ctx context.Context, id string) (GetCandidateRow, error) {
	row := q.db.QueryRow(ctx, getCandidate, id)
	var i GetCandidateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.Preferences,
	)
	return i, err
}

const getCandidateByUserID = `-- name: GetCandidateByUserID :one
SELECT id, user_id, location, preferences FROM candidates WHERE user_id = $1
`

type GetCandidateByUserIDRow struct {
	ID          string
	UserID      string
	Location    pgtype.Text
	Preferences []byte
}

func (q *Queries) GetCandidateByUserID(ctx context.Context, userID string) (GetCandidateByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCandidateByUserID, userID)
	var i GetCandidateByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.Preferences,
	)
	return i, err
}

const listCandidates = `-- name: ListCandidates :many
SELECT id, user_id, location, preferences FROM candidates ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListCandidatesParams struct {
	Limit  int32
	Offset int32
}

type ListCandidatesRow struct {
	ID          string
	UserID      string
	Location    pgtype.Text
	Preferences []byte
}

func (q *Queries) ListCandidates(ctx context.Context, arg ListCandidatesParams) ([]ListCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCandidates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesRow
	for rows.Next() {
		var i ListCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Location,
			&i.Preferences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCandidate = `-- name: UpdateCandidate :execrows
UPDATE candidates SET location = $2, preferences = $3 WHERE id = $1
`

type UpdateCandidateParams struct {
	ID          string
	Location    pgtype.Text
	Preferences []byte
}

func (q *Queries) UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCandidate, arg.ID, arg.Location, arg.Preferences)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
