// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employers.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployer = `-- name: CreateEmployer :exec
INSERT INTO employers (id, company_name, contact_user_id, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type CreateEmployerParams struct {
	ID            string
	CompanyName   string
	ContactUserID pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateEmployer(ctx context.Context, arg CreateEmployerParams) error {
	_, err := q.db.Exec(ctx, createEmployer,
		arg.ID,
		arg.CompanyName,
		arg.ContactUserID,
		arg.CreatedAt,
	)
	return err
}

const getEmployerByContactUser = `-- name: GetEmployerByContactUser :one
SELECT id, company_name, contact_user_id, created_at
FROM employers
WHERE contact_user_id = $1
`

func (q *Queries) GetEmployerByContactUser(ctx context.Context, contactUserID pgtype.Text) (Employer, error) {
	row := q.db.QueryRow(ctx, getEmployerByContactUser, contactUserID)
	var i Employer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.ContactUserID,
		&i.CreatedAt,
	)
	return i, err
}
