// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: erasure.sql

package sqlcdb

import (
	"context"
)

const anonymizeUser = `-- name: AnonymizeUser :exec
UPDATE users SET name = '', password_hash = '', email = $2 WHERE id = $1
`

type AnonymizeUserParams struct {
	ID    string
	Email string
}

func (q *Queries) AnonymizeUser(ctx context.Context, arg AnonymizeUserParams) error {
	_, err := q.db.Exec(ctx, anonymizeUser, arg.ID, arg.Email)
	return err
}

const deleteApplicationsByCandidate = `-- name: DeleteApplicationsByCandidate :exec
DELETE FROM applications WHERE candidate_id = $1
`

func (q *Queries) DeleteApplicationsByCandidate(ctx context.Context, candidateID string) error {
	_, err := q.db.Exec(ctx, deleteApplicationsByCandidate, candidateID)
	return err
}

const deleteCandidate = `-- name: DeleteCandidate :exec

DELETE FROM candidates WHERE id = $1
`

// Right-to-erasure + retention hard-delete primitives (CAL-118 / CAL-158).
// Deleting a candidate cascades to its profiles, matches, interviews, and
// applications via ON DELETE CASCADE; the scoped deletes below are still run
// explicitly so the erasure cascade is honoured even where a store is not the
// database. The user row is retained-but-anonymised (it may be referenced), and
// the append-only audit trail is retained-but-tombstoned.
func (q *Queries) DeleteCandidate(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCandidate, id)
	return err
}

const deleteMatchesByCandidate = `-- name: DeleteMatchesByCandidate :exec
DELETE FROM matches WHERE candidate_id = $1
`

func (q *Queries) DeleteMatchesByCandidate(ctx context.Context, candidateID string) error {
	_, err := q.db.Exec(ctx, deleteMatchesByCandidate, candidateID)
	return err
}

const deleteTalentProfilesByCandidate = `-- name: DeleteTalentProfilesByCandidate :exec
DELETE FROM talent_profiles WHERE candidate_id = $1
`

func (q *Queries) DeleteTalentProfilesByCandidate(ctx context.Context, candidateID string) error {
	_, err := q.db.Exec(ctx, deleteTalentProfilesByCandidate, candidateID)
	return err
}

const tombstoneAuditActor = `-- name: TombstoneAuditActor :exec
UPDATE audit_log SET actor_user_id = 'erased' WHERE actor_user_id = $1
`

func (q *Queries) TombstoneAuditActor(ctx context.Context, actorUserID string) error {
	_, err := q.db.Exec(ctx, tombstoneAuditActor, actorUserID)
	return err
}
