// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interviews.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInterviewsByCandidate = `-- name: CountInterviewsByCandidate :one
SELECT count(*) FROM talent_interviews WHERE candidate_id = $1
`

func (q *Queries) CountInterviewsByCandidate(ctx context.Context, candidateID string) (int64, error) {
	row := q.db.QueryRow(ctx, countInterviewsByCandidate, candidateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInterview = `-- name: CreateInterview :exec
INSERT INTO talent_interviews (id, role_id, candidate_id, mode, status, report_card, confidence, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateInterviewParams struct {
	ID          string
	RoleID      string
	CandidateID string
	Mode        string
	Status      string
	ReportCard  []byte
	Confidence  pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateInterview(ctx context.Context, arg CreateInterviewParams) error {
	_, err := q.db.Exec(ctx, createInterview,
		arg.ID,
		arg.RoleID,
		arg.CandidateID,
		arg.Mode,
		arg.Status,
		arg.ReportCard,
		arg.Confidence,
		arg.CreatedAt,
	)
	return err
}

const deleteInterviewTurns = `-- name: DeleteInterviewTurns :exec
DELETE FROM interview_turns WHERE interview_id = $1
`

func (q *Queries) DeleteInterviewTurns(ctx context.Context, interviewID string) error {
	_, err := q.db.Exec(ctx, deleteInterviewTurns, interviewID)
	return err
}

const deleteInterviewsByCandidate = `-- name: DeleteInterviewsByCandidate :exec
DELETE FROM talent_interviews WHERE candidate_id = $1
`

func (q *Queries) DeleteInterviewsByCandidate(ctx context.Context, candidateID string) error {
	_, err := q.db.Exec(ctx, deleteInterviewsByCandidate, candidateID)
	return err
}

const getInterview = `-- name: GetInterview :one
SELECT id, role_id, candidate_id, mode, status, report_card, confidence, created_at
FROM talent_interviews WHERE id = $1
`

func (q *Queries) GetInterview(ctx context.Context, id string) (TalentInterview, error) {
	row := q.db.QueryRow(ctx, getInterview, id)
	var i TalentInterview
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.CandidateID,
		&i.Mode,
		&i.Status,
		&i.ReportCard,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const insertInterviewTurn = `-- name: InsertInterviewTurn :exec
INSERT INTO interview_turns (id, interview_id, ordinal, question, answer, competency_tag)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertInterviewTurnParams struct {
	ID            string
	InterviewID   string
	Ordinal       int32
	Question      string
	Answer        pgtype.Text
	CompetencyTag pgtype.Text
}

func (q *Queries) InsertInterviewTurn(ctx context.Context, arg InsertInterviewTurnParams) error {
	_, err := q.db.Exec(ctx, insertInterviewTurn,
		arg.ID,
		arg.InterviewID,
		arg.Ordinal,
		arg.Question,
		arg.Answer,
		arg.CompetencyTag,
	)
	return err
}

const listInterviewTurns = `-- name: ListInterviewTurns :many
SELECT id, interview_id, ordinal, question, answer, competency_tag
FROM interview_turns WHERE interview_id = $1 ORDER BY ordinal
`

func (q *Queries) ListInterviewTurns(ctx context.Context, interviewID string) ([]InterviewTurn, error) {
	rows, err := q.db.Query(ctx, listInterviewTurns, interviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InterviewTurn
	for rows.Next() {
		var i InterviewTurn
		if err := rows.Scan(
			&i.ID,
			&i.InterviewID,
			&i.Ordinal,
			&i.Question,
			&i.Answer,
			&i.CompetencyTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterviewsByCandidate = `-- name: ListInterviewsByCandidate :many
SELECT id, role_id, candidate_id, mode, status, report_card, confidence, created_at
FROM talent_interviews WHERE candidate_id = $1
ORDER BY created_at DESC, id LIMIT $2 OFFSET $3
`

type ListInterviewsByCandidateParams struct {
	CandidateID string
	Limit       int32
	Offset      int32
}

func (q *Queries) ListInterviewsByCandidate(ctx context.Context, arg ListInterviewsByCandidateParams) ([]TalentInterview, error) {
	rows, err := q.db.Query(ctx, listInterviewsByCandidate, arg.CandidateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TalentInterview
	for rows.Next() {
		var i TalentInterview
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.CandidateID,
			&i.Mode,
			&i.Status,
			&i.ReportCard,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterview = `-- name: UpdateInterview :execrows
UPDATE talent_interviews
SET mode = $2, status = $3, report_card = $4, confidence = $5
WHERE id = $1
`

type UpdateInterviewParams struct {
	ID         string
	Mode       string
	Status     string
	ReportCard []byte
	Confidence pgtype.Text
}

func (q *Queries) UpdateInterview(ctx context.Context, arg UpdateInterviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInterview,
		arg.ID,
		arg.Mode,
		arg.Status,
		arg.ReportCard,
		arg.Confidence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
