// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMatchesByCandidate = `-- name: CountMatchesByCandidate :one
SELECT count(*) FROM matches WHERE candidate_id = $1
`

func (q *Queries) CountMatchesByCandidate(ctx context.Context, candidateID string) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchesByCandidate, candidateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMatchesByRole = `-- name: CountMatchesByRole :one
SELECT count(*) FROM matches WHERE role_id = $1
`

func (q *Queries) CountMatchesByRole(ctx context.Context, roleID string) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchesByRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMatchesByCandidate = `-- name: ListMatchesByCandidate :many
SELECT id, role_id, candidate_id, overall_score, confidence, breakdown, rationale, watch_outs, thin_evidence_flag, created_at
FROM matches WHERE candidate_id = $1 ORDER BY overall_score DESC LIMIT $2 OFFSET $3
`

type ListMatchesByCandidateParams struct {
	CandidateID string
	Limit       int32
	Offset      int32
}

func (q *Queries) ListMatchesByCandidate(ctx context.Context, arg ListMatchesByCandidateParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByCandidate, arg.CandidateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.CandidateID,
			&i.OverallScore,
			&i.Confidence,
			&i.Breakdown,
			&i.Rationale,
			&i.WatchOuts,
			&i.ThinEvidenceFlag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByRole = `-- name: ListMatchesByRole :many
SELECT id, role_id, candidate_id, overall_score, confidence, breakdown, rationale, watch_outs, thin_evidence_flag, created_at
FROM matches WHERE role_id = $1 ORDER BY overall_score DESC LIMIT $2 OFFSET $3
`

type ListMatchesByRoleParams struct {
	RoleID string
	Limit  int32
	Offset int32
}

func (q *Queries) ListMatchesByRole(ctx context.Context, arg ListMatchesByRoleParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByRole, arg.RoleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.CandidateID,
			&i.OverallScore,
			&i.Confidence,
			&i.Breakdown,
			&i.Rationale,
			&i.WatchOuts,
			&i.ThinEvidenceFlag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMatch = `-- name: UpsertMatch :exec
INSERT INTO matches (id, role_id, candidate_id, overall_score, confidence, breakdown, rationale, watch_outs, thin_evidence_flag, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (role_id, candidate_id) DO UPDATE SET
  overall_score = EXCLUDED.overall_score,
  confidence = EXCLUDED.confidence,
  breakdown = EXCLUDED.breakdown,
  rationale = EXCLUDED.rationale,
  watch_outs = EXCLUDED.watch_outs,
  thin_evidence_flag = EXCLUDED.thin_evidence_flag
`

type UpsertMatchParams struct {
	ID               string
	RoleID           string
	CandidateID      string
	OverallScore     float64
	Confidence       string
	Breakdown        []byte
	Rationale        pgtype.Text
	WatchOuts        []byte
	ThinEvidenceFlag bool
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) error {
	_, err := q.db.Exec(ctx, upsertMatch,
		arg.ID,
		arg.RoleID,
		arg.CandidateID,
		arg.OverallScore,
		arg.Confidence,
		arg.Breakdown,
		arg.Rationale,
		arg.WatchOuts,
		arg.ThinEvidenceFlag,
	)
	return err
}
