// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Application struct {
	ID              string
	RoleID          string
	CandidateID     string
	ProfileID       pgtype.Text
	Source          string
	TailoredSummary pgtype.Text
	Status          string
	CreatedAt       pgtype.Timestamptz
}

type AuditLog struct {
	ID          string
	ActorUserID string
	Action      string
	Entity      string
	EntityID    string
	BeforeJson  []byte
	AfterJson   []byte
	CreatedAt   pgtype.Timestamptz
}

type Candidate struct {
	ID          string
	UserID      string
	Location    pgtype.Text
	Preferences []byte
	CreatedAt   pgtype.Timestamptz
}

type Employer struct {
	ID            string
	CompanyName   string
	ContactUserID pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type InterviewTurn struct {
	ID            string
	InterviewID   string
	Ordinal       int32
	Question      string
	Answer        pgtype.Text
	CompetencyTag pgtype.Text
}

type Match struct {
	ID               string
	RoleID           string
	CandidateID      string
	OverallScore     float64
	Confidence       string
	Breakdown        []byte
	Rationale        pgtype.Text
	WatchOuts        []byte
	ThinEvidenceFlag bool
	CreatedAt        pgtype.Timestamptz
}

type Role struct {
	ID            string
	EmployerID    string
	Title         string
	Status        string
	RoleSpec      []byte
	Rubric        []byte
	SalaryBand    []byte
	RoleEmbedding pgvector.Vector
	CreatedAt     pgtype.Timestamptz
}

type TalentInterview struct {
	ID          string
	RoleID      string
	CandidateID string
	Mode        string
	Status      string
	ReportCard  []byte
	Confidence  pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type TalentProfile struct {
	ID               string
	CandidateID      string
	CvText           pgtype.Text
	Summary          pgtype.Text
	Profile          []byte
	ProfileEmbedding pgvector.Vector
	PassportStatus   string
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID           string
	Email        string
	Role         string
	Name         string
	PasswordHash string
	Status       string
	CreatedAt    pgtype.Timestamptz
}
