// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE refresh_tokens SET revoked = true
WHERE id = $1 AND NOT revoked AND expires_at > $2
RETURNING id, user_id, expires_at
`

type ConsumeRefreshTokenParams struct {
	ID  string
	Now pgtype.Timestamptz
}

type ConsumeRefreshTokenRow struct {
	ID        string
	UserID    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ConsumeRefreshToken(ctx context.Context, arg ConsumeRefreshTokenParams) (ConsumeRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, arg.ID, arg.Now)
	var i ConsumeRefreshTokenRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = true WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const saveRefreshToken = `-- name: SaveRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, expires_at, revoked)
VALUES ($1, $2, $3, false)
`

type SaveRefreshTokenParams struct {
	ID        string
	UserID    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, saveRefreshToken, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}
