// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRetentionEligibleCandidates = `-- name: ListRetentionEligibleCandidates :many
SELECT id FROM users WHERE role = 'candidate' AND created_at <= $1 ORDER BY created_at
`

// Candidate-role users whose account was created on or before the cutoff — i.e.
// whose personal data has aged past the retention window (CAL-158). Candidate age
// is taken from the owning user because talent.Candidate carries no timestamp and
// a registered candidate's id equals their user id.
func (q *Queries) ListRetentionEligibleCandidates(ctx context.Context, createdAt pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, listRetentionEligibleCandidates, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
