// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRolesByEmployer = `-- name: CountRolesByEmployer :one
SELECT count(*) FROM roles WHERE employer_id = $1
`

func (q *Queries) CountRolesByEmployer(ctx context.Context, employerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRolesByEmployer, employerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (id, employer_id, title, status, role_spec, rubric, salary_band, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateRoleParams struct {
	ID         string
	EmployerID string
	Title      string
	Status     string
	RoleSpec   []byte
	Rubric     []byte
	SalaryBand []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.ID,
		arg.EmployerID,
		arg.Title,
		arg.Status,
		arg.RoleSpec,
		arg.Rubric,
		arg.SalaryBand,
		arg.CreatedAt,
	)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, employer_id, title, status, role_spec, rubric, salary_band, created_at
FROM roles
WHERE id = $1
`

type GetRoleRow struct {
	ID         string
	EmployerID string
	Title      string
	Status     string
	RoleSpec   []byte
	Rubric     []byte
	SalaryBand []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetRole(ctx context.Context, id string) (GetRoleRow, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i GetRoleRow
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.Title,
		&i.Status,
		&i.RoleSpec,
		&i.Rubric,
		&i.SalaryBand,
		&i.CreatedAt,
	)
	return i, err
}

const listRolesByEmployer = `-- name: ListRolesByEmployer :many
SELECT id, employer_id, title, status, role_spec, rubric, salary_band, created_at
FROM roles
WHERE employer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRolesByEmployerParams struct {
	EmployerID string
	Limit      int32
	Offset     int32
}

type ListRolesByEmployerRow struct {
	ID         string
	EmployerID string
	Title      string
	Status     string
	RoleSpec   []byte
	Rubric     []byte
	SalaryBand []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListRolesByEmployer(ctx context.Context, arg ListRolesByEmployerParams) ([]ListRolesByEmployerRow, error) {
	rows, err := q.db.Query(ctx, listRolesByEmployer, arg.EmployerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesByEmployerRow
	for rows.Next() {
		var i ListRolesByEmployerRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployerID,
			&i.Title,
			&i.Status,
			&i.RoleSpec,
			&i.Rubric,
			&i.SalaryBand,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE roles
SET title = $2, status = $3, role_spec = $4, rubric = $5, salary_band = $6
WHERE id = $1
`

type UpdateRoleParams struct {
	ID         string
	Title      string
	Status     string
	RoleSpec   []byte
	Rubric     []byte
	SalaryBand []byte
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRole,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.RoleSpec,
		arg.Rubric,
		arg.SalaryBand,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
