// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: talent_profiles.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTalentProfiles = `-- name: CountTalentProfiles :one
SELECT count(*) FROM talent_profiles
`

func (q *Queries) CountTalentProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTalentProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTalentProfile = `-- name: CreateTalentProfile :exec
INSERT INTO talent_profiles (id, candidate_id, summary, profile, passport_status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTalentProfileParams struct {
	ID             string
	CandidateID    string
	Summary        pgtype.Text
	Profile        []byte
	PassportStatus string
}

func (q *Queries) CreateTalentProfile(ctx context.Context, arg CreateTalentProfileParams) error {
	_, err := q.db.Exec(ctx, createTalentProfile,
		arg.ID,
		arg.CandidateID,
		arg.Summary,
		arg.Profile,
		arg.PassportStatus,
	)
	return err
}

const getTalentProfile = `-- name: GetTalentProfile :one
SELECT id, candidate_id, summary, profile, passport_status FROM talent_profiles WHERE id = $1
`

type GetTalentProfileRow struct {
	ID             string
	CandidateID    string
	Summary        pgtype.Text
	Profile        []byte
	PassportStatus string
}

func (q *Queries) GetTalentProfile(ctx context.Context, id string) (GetTalentProfileRow, error) {
	row := q.db.QueryRow(ctx, getTalentProfile, id)
	var i GetTalentProfileRow
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.Summary,
		&i.Profile,
		&i.PassportStatus,
	)
	return i, err
}

const getTalentProfileByCandidateID = `-- name: GetTalentProfileByCandidateID :one
SELECT id, candidate_id, summary, profile, passport_status FROM talent_profiles WHERE candidate_id = $1
`

type GetTalentProfileByCandidateIDRow struct {
	ID             string
	CandidateID    string
	Summary        pgtype.Text
	Profile        []byte
	PassportStatus string
}

func (q *Queries) GetTalentProfileByCandidateID(ctx context.Context, candidateID string) (GetTalentProfileByCandidateIDRow, error) {
	row := q.db.QueryRow(ctx, getTalentProfileByCandidateID, candidateID)
	var i GetTalentProfileByCandidateIDRow
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.Summary,
		&i.Profile,
		&i.PassportStatus,
	)
	return i, err
}

const listTalentProfiles = `-- name: ListTalentProfiles :many
SELECT id, candidate_id, summary, profile, passport_status FROM talent_profiles ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListTalentProfilesParams struct {
	Limit  int32
	Offset int32
}

type ListTalentProfilesRow struct {
	ID             string
	CandidateID    string
	Summary        pgtype.Text
	Profile        []byte
	PassportStatus string
}

func (q *Queries) ListTalentProfiles(ctx context.Context, arg ListTalentProfilesParams) ([]ListTalentProfilesRow, error) {
	rows, err := q.db.Query(ctx, listTalentProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTalentProfilesRow
	for rows.Next() {
		var i ListTalentProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.Summary,
			&i.Profile,
			&i.PassportStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTalentProfile = `-- name: UpdateTalentProfile :execrows
UPDATE talent_profiles SET summary = $2, profile = $3, passport_status = $4 WHERE id = $1
`

type UpdateTalentProfileParams struct {
	ID             string
	Summary        pgtype.Text
	Profile        []byte
	PassportStatus string
}

func (q *Queries) UpdateTalentProfile(ctx context.Context, arg UpdateTalentProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTalentProfile,
		arg.ID,
		arg.Summary,
		arg.Profile,
		arg.PassportStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
